测试 CI

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -25,31 +25,47 @@ jobs:
   meta:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          submodules: true
-      - id: set_tag
-        run: |
-          is_release=${{ startsWith(github.ref, 'refs/tags/v') }}
-          tag=$(git describe --tags --match "v*" ${{ github.ref }} || true)
-          if [[ $tag != v* ]]; then
-            tag=$(curl -sX GET "https://api.github.com/repos/${{ github.repository }}/releases/latest" --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | awk '/tag_name/{print $4}' FS='["]')
-            if [[ $tag != v* ]]; then
-              tag="v0.0.0"
-            fi
-            tag=$(date "+$tag-%y%m%d-$(git rev-parse --short HEAD)")
-          fi
-          if ! $($is_release) ; then
-            prefix=${tag%-*-*}
-            suffix=${tag#$prefix-}
-            tag="$prefix-ci.$suffix"
-          fi
-          echo tag=$tag | tee -a $GITHUB_OUTPUT
-          echo is_release=$is_release | tee -a $GITHUB_OUTPUT
+        - uses: actions/checkout@v4
+          with:
+              fetch-depth: 0
+        - id: set
+          run: |
+              is_release=${{ startsWith(github.ref, 'refs/tags/v') }}
+              is_pre_release=${{ contains(github.ref, '-alpha.') || contains(github.ref, '-beta.') || contains(github.ref, '-rc.') }}
+              commit_hash=$(git rev-parse --short HEAD)
+
+              if $is_release; then
+                tag=$(git describe --tags || true)
+              else
+                tag=$(git describe --tags --match "v*" --exclude "*-post*" || true)
+              fi
+              if [[ $tag != v* ]]; then
+                if $is_release; then echo "::error::Failed to get tag on releasing" && exit 1; fi
+                ver_core=$(curl -sX GET "https://api.github.com/repos/MaaXYZ/MaaFramework/releases/latest" --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | awk '/tag_name/{print $4}' FS='["]' || true)
+                tag=$(date "+$ver_core-1%m%d-${commit_hash}")
+                if [[ $tag != v* ]]; then
+                  tag=$(date "+v%Y.%-m.%-d-2%H%M-${commit_hash}")
+                fi
+              fi
+
+              if $is_release; then
+                version=${tag#v}
+              else
+                ver_core=${tag%-*-*}
+                suffixs=(${tag//-/ })
+                tag=${ver_core}-post.${suffixs[-2]}-ci.${{ github.run_id }}
+                version=${tag#v}+${commit_hash}.$(date +%Y%m%d)
+              fi
+
+              echo "tag=$tag
+              version=$version
+              is_release=$is_release
+              is_pre_release=$is_pre_release" | tee -a "$GITHUB_OUTPUT"
     outputs:
-      tag: ${{ steps.set_tag.outputs.tag }}
-      is_release: ${{ steps.set_tag.outputs.is_release }}
+        is_release: ${{ steps.set.outputs.is_release }}
+        is_pre_release: ${{ steps.set.outputs.is_pre_release }}
+        tag: ${{ steps.set.outputs.tag }} # v<release version> | v<ci version>
+        version: ${{ steps.set.outputs.version }} # <release version> | <ci version>+<build> e.g
 
   Windows:
     needs: meta
@@ -127,6 +143,7 @@ jobs:
       - uses: actions/download-artifact@v4
         with:
           path: assets
+          
 
       - run: |
           cd assets
@@ -137,3 +154,4 @@ jobs:
         with:
           files: assets/*
           tag_name: ${{ needs.meta.outputs.tag }}
+          prerelease: ${{ needs.meta.outputs.is_pre_release == 'true' }}
